//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.LoginData
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class LoginData { }
#else

	public class LoginData : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public LoginData()
		{
			try
			{
				Uri resourceUri = new Uri("/PhoneApp1;component/SampleData/LoginData/LoginData.xaml", UriKind.RelativeOrAbsolute);
				System.Windows.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _LoginName = string.Empty;

		public string LoginName
		{
			get
			{
				return this._LoginName;
			}

			set
			{
				if (this._LoginName != value)
				{
					this._LoginName = value;
					this.OnPropertyChanged("LoginName");
				}
			}
		}

		private bool _IsStudent = false;

		public bool IsStudent
		{
			get
			{
				return this._IsStudent;
			}

			set
			{
				if (this._IsStudent != value)
				{
					this._IsStudent = value;
					this.OnPropertyChanged("IsStudent");
				}
			}
		}

		private string _Password = string.Empty;

		public string Password
		{
			get
			{
				return this._Password;
			}

			set
			{
				if (this._Password != value)
				{
					this._Password = value;
					this.OnPropertyChanged("Password");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
